# Generated by Django 4.0.4 on 2022-05-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('question_date', models.DateTimeField(verbose_name='publication date for this poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
                ('total_votes', models.IntegerField()),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pollquestion')),
            ],
        ),
    ]
